In [1]:
import  numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
%matplotlib inline 
import warnings
warnings.filterwarnings("ignore")

In [2]:
X_train = pd.read_csv("x-train.csv")
x_test = pd.read_csv("x_test.csv")
y_train_list  = pd.read_csv("y_train.csv")
y_train_list.fillna( 0.  ,inplace = True)
y_train_list= y_train_list.astype("int32")

In [3]:
labels = y_train_list.columns.to_list()
codepers = X_train.ncodpers.to_list()

In [4]:
from collections import defaultdict 
activate_map =  defaultdict( list )
for idx  , row in  y_train_list.iterrows() :
    for  j , label in  enumerate(labels) :
        if row[label]!=0 :
            if   not j  in  activate_map[codepers[idx]]:
                activate_map[codepers[idx]].append(j ) # 加入编号
        else :
            continue 

In [5]:
activate_map 

defaultdict(list,
            {1050676: [2, 12, 23],
             1050662: [2, 12, 19],
             1050652: [4, 12, 19, 23, 21, 22],
             1050489: [2],
             1050490: [2],
             1050497: [2],
             1050500: [2],
             1050501: [2],
             1050556: [2],
             1050536: [2],
             1050544: [2],
             1050713: [2],
             1050847: [2],
             1050811: [2, 23],
             1050829: [2],
             1050797: [2],
             1050208: [2],
             1050222: [2],
             1050288: [2],
             1050267: [2],
             1050137: [2],
             1050094: [2],
             1050198: [2],
             1050173: [2],
             1050425: [2],
             1050401: [2],
             1050463: [2, 23],
             1050373: [2],
             1051914: [2],
             1051847: [2],
             1051944: [2],
             1051794: [2, 12, 23],
             1051831: [12, 2, 23, 4, 21, 22],
             1051793

In [6]:
import time 
from lightgbm import LGBMClassifier
import lightgbm as lgb 
from  sklearn.model_selection import train_test_split 
predict_list = [] 
for label in labels : 
    print ("正在训练 ， " ,label )
    start = time.time()
    y = y_train_list[label]
    x_train ,x_valid ,y_train , y_valid = train_test_split(X_train ,
                                                            y,
                                                       test_size = 0.2)

    params= {'boosting_type':'gbdt',
        'objective' : 'binary', #任务类型
        'metric' : 'auc', #评估指标
        'learning_rate' : 0.01, #学习率
        'max_depth' : 10, #树的最大深度
        'feature_fraction':0.8, #设置在每次迭代中使用特征的比例
        'bagging_fraction': 0.9, #样本采样比例
        'bagging_freq': 8, #bagging的次数
        'lambda_l1': 0.6, #L1正则
        'lambda_l2': 0, #L2正则
    }
    
    train_data = lgb.Dataset(x_train, label=y_train)
    valid_data = lgb.Dataset(x_valid, label=y_valid)
    model = lgb.train(params,
                      train_data,
                      valid_sets=[train_data,valid_data],
                      num_boost_round =500 ,
                      early_stopping_rounds=200,
                      verbose_eval=25)
    predict=model.predict(x_test)
    predict = pd.Series(predict).map(  lambda x :1 if x> 0.5 else 0 )
    predict_list.append(predict.values) 
    print ( time.time() - start )       

正在训练 ，  ind_ahor_fin_ult1
Training until validation scores don't improve for 200 rounds
[25]	training's auc: 0.999999	valid_1's auc: 1
[50]	training's auc: 0.999999	valid_1's auc: 1
[75]	training's auc: 0.999999	valid_1's auc: 1
[100]	training's auc: 0.999999	valid_1's auc: 1
[125]	training's auc: 0.999999	valid_1's auc: 1
[150]	training's auc: 0.999999	valid_1's auc: 1
[175]	training's auc: 0.999999	valid_1's auc: 1
[200]	training's auc: 0.999999	valid_1's auc: 1
Early stopping, best iteration is:
[5]	training's auc: 0.999999	valid_1's auc: 1
9.49161696434021
正在训练 ，  ind_aval_fin_ult1
Training until validation scores don't improve for 200 rounds
[25]	training's auc: 0.769048	valid_1's auc: 0.666445
[50]	training's auc: 0.769201	valid_1's auc: 0.666542
[75]	training's auc: 0.769231	valid_1's auc: 0.666614
[100]	training's auc: 0.769236	valid_1's auc: 0.666623
[125]	training's auc: 0.769236	valid_1's auc: 0.666629
[150]	training's auc: 0.769237	valid_1's auc: 0.666629
[175]	training's a

[350]	training's auc: 0.93118	valid_1's auc: 0.929269
[375]	training's auc: 0.931752	valid_1's auc: 0.929806
[400]	training's auc: 0.93239	valid_1's auc: 0.930398
[425]	training's auc: 0.933085	valid_1's auc: 0.931029
[450]	training's auc: 0.933817	valid_1's auc: 0.931716
[475]	training's auc: 0.934572	valid_1's auc: 0.932452
[500]	training's auc: 0.935394	valid_1's auc: 0.933246
Did not meet early stopping. Best iteration is:
[500]	training's auc: 0.935394	valid_1's auc: 0.933246
49.74336528778076
正在训练 ，  ind_ctpp_fin_ult1
Training until validation scores don't improve for 200 rounds
[25]	training's auc: 0.926644	valid_1's auc: 0.927474
[50]	training's auc: 0.931137	valid_1's auc: 0.931561
[75]	training's auc: 0.934681	valid_1's auc: 0.935235
[100]	training's auc: 0.937319	valid_1's auc: 0.93749
[125]	training's auc: 0.939671	valid_1's auc: 0.939667
[150]	training's auc: 0.942125	valid_1's auc: 0.942016
[175]	training's auc: 0.944062	valid_1's auc: 0.943915
[200]	training's auc: 0.945

57.99690794944763
正在训练 ，  ind_hip_fin_ult1
Training until validation scores don't improve for 200 rounds
[25]	training's auc: 0.96937	valid_1's auc: 0.970221
[50]	training's auc: 0.976992	valid_1's auc: 0.978263
[75]	training's auc: 0.987632	valid_1's auc: 0.990363
[100]	training's auc: 0.990021	valid_1's auc: 0.994176
[125]	training's auc: 0.995353	valid_1's auc: 0.995062
[150]	training's auc: 0.996057	valid_1's auc: 0.995731
[175]	training's auc: 0.996416	valid_1's auc: 0.995996
[200]	training's auc: 0.99679	valid_1's auc: 0.996261
[225]	training's auc: 0.996999	valid_1's auc: 0.996453
[250]	training's auc: 0.997348	valid_1's auc: 0.996862
[275]	training's auc: 0.997585	valid_1's auc: 0.997087
[300]	training's auc: 0.997761	valid_1's auc: 0.997301
[325]	training's auc: 0.998112	valid_1's auc: 0.997785
[350]	training's auc: 0.998259	valid_1's auc: 0.998003
[375]	training's auc: 0.998404	valid_1's auc: 0.998252
[400]	training's auc: 0.998579	valid_1's auc: 0.998604
[425]	training's auc

[175]	training's auc: 0.997856	valid_1's auc: 0.996781
[200]	training's auc: 0.998169	valid_1's auc: 0.997124
[225]	training's auc: 0.998436	valid_1's auc: 0.997231
[250]	training's auc: 0.999264	valid_1's auc: 0.997804
[275]	training's auc: 0.999449	valid_1's auc: 0.997988
[300]	training's auc: 0.999572	valid_1's auc: 0.998032
[325]	training's auc: 0.999615	valid_1's auc: 0.998088
[350]	training's auc: 0.999676	valid_1's auc: 0.998175
[375]	training's auc: 0.999752	valid_1's auc: 0.998281
[400]	training's auc: 0.999785	valid_1's auc: 0.998222
[425]	training's auc: 0.999822	valid_1's auc: 0.998066
[450]	training's auc: 0.999844	valid_1's auc: 0.998103
[475]	training's auc: 0.999856	valid_1's auc: 0.998129
[500]	training's auc: 0.999883	valid_1's auc: 0.99819
Did not meet early stopping. Best iteration is:
[500]	training's auc: 0.999883	valid_1's auc: 0.99819
61.86483073234558
正在训练 ，  ind_nomina_ult1
Training until validation scores don't improve for 200 rounds
[25]	training's auc: 0.89

In [7]:
predict_list

[array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([1, 1, 1, ..., 1, 1, 1], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 1, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dt

In [8]:
x_test

fecha_dato  ncodpers  ind_empleado  pais_residencia  sexo  age  \
0              16    657788             3               15     0   23   
1              16    657794             3               15     0   23   
2              16    657770             3               15     1   23   
3              16    658056             3               15     1   23   
4              16    657869             3               15     1   23   
...           ...       ...           ...              ...   ...  ...   
29157          16   1166847             3               15     1   23   
29158          16   1166605             3               15     1   23   
29159          16   1166829             3               15     1   23   
29160          16   1166827             3               15     0   23   
29161          16   1166781             3               15     0   23   

       fecha_alta  ind_nuevo  antiguedad  indrel  ...          renta  \
0            2986          0          21       0  ...  132559.350000   
1            2986          0          21       0  ...  102189.000000   
2            2986          0          21       0  ...  136573.351323   
3            2988          0          21       0  ...   64681.020000   
4            2986          0          21       0  ...  115372.500000   
...           ...        ...         ...     ...  ...            ...   
29157        4883          0          21       0  ...  136573.351323   
29158        4883          0          21       0  ...   92776.650000   
29159        4883          0          21       0  ...   96488.880000   
29160        4883          0          21       0  ...   30303.420000   
29161        4883          0          21       0  ...   66748.500000   

       segmento  fecha_alta_year  fecha_alta_month  fecha_alta_day  \
0             1             2006                11              18   
1             0             2006                11              18   
2             1             2006                11              18   
3             2             2006                11              20   
4             1             2006                11              18   
...         ...              ...               ...             ...   
29157         2             2013                 8              14   
29158         2             2013                 8              14   
29159         2             2013                 8              14   
29160         2             2013                 8              14   
29161         2             2013                 8              14   

       fecha_alta_weekday  fecha_dato_year  fecha_dato_month  fecha_dato_day  \
0                       5             2016                 5              28   
1                       5             2016                 5              28   
2                       5             2016                 5              28   
3                       0             2016                 5              28   
4                       5             2016                 5              28   
...                   ...              ...               ...             ...   
29157                   2             2016                 5              28   
29158                   2             2016                 5              28   
29159                   2             2016                 5              28   
29160                   2             2016                 5              28   
29161                   2             2016                 5              28   

       fecha_dato_weekday  
0                       5  
1                       5  
2                       5  
3                       5  
4                       5  
...                   ...  
29157                   5  
29158                   5  
29159                   5  
29160                   5  
29161                   5  

[29162 rows x 28 columns]

In [9]:
predict = np.array(  predict_list).T

In [10]:
predict

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], dtype=int64)

In [11]:
to_list =[] # 预测列表
for idx , line in enumerate(predict):
    temp =  np.argwhere(  line ==1 ).ravel()
    l = []
    if  len(temp) >0 :
        for  j in temp :
            if j not in activate_map[idx] :
                l.append(  labels[j])
    to_list.append(l )

In [12]:
x_test['added_products']  = pd.Series(to_list).map( lambda x : ' '.join(x))

In [13]:
x_test[['ncodpers' ,"added_products"]].to_csv('submition.csv' ,index = False)

In [16]:
x_test[['ncodpers' ,"added_products"]].sort_values("ncodpers").to_csv('submition1.csv' ,index = False)

In [17]:
x_test[['ncodpers' ,"added_products"]]

ncodpers                      added_products
0        657788                    ind_cco_fin_ult1
1        657794  ind_cco_fin_ult1 ind_dela_fin_ult1
2        657770                    ind_cco_fin_ult1
3        658056                    ind_cco_fin_ult1
4        657869                    ind_cco_fin_ult1
...         ...                                 ...
29157   1166847                    ind_cco_fin_ult1
29158   1166605                    ind_cco_fin_ult1
29159   1166829                    ind_cco_fin_ult1
29160   1166827                    ind_cco_fin_ult1
29161   1166781                    ind_cco_fin_ult1

[29162 rows x 2 columns]